### ISSUE TITLE
AWS -`LambdaInvoke` task

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-aws#149]

**Comment by anna-geller** [comment]
this might be [a good starting point](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/lambda/LambdaClient.html)

**Comment by Ben8t** [comment]
Maybe naive question, but couln't be possible to call the Lambda function via a HTTP call thanks with the corresponding Kestra task https://kestra.io/plugins/plugin-fs/tasks/http/io.kestra.plugin.fs.http.request 🤔 ?

Like, I believe AWS Lambda can send a response only when the process is finished isn't ?

**Comment by Ben8t** [comment]
Though I agree with a broader vision: you might want to trigger a Kestra flow as soon as an async AWS Lambda run finish for example.

**Comment by anna-geller** [comment]
I know that @loicmathieu recommends using the officially supported Java SDK, such as the one provided by AWS, when possible, so this is why I suggested it. Up to the development team to figure out the right solution

**Comment by loicmathieu** [comment]
Done via #238

**Comment by anna-geller** [comment]
man I was editing the issue :D
