### ISSUE TITLE
If no explicit credentials are provided, use either environment variables, local .aws/credentials profile or IAM role

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#347]
### Feature description

IIRC most if not all of that is already supported by the `DefaultCredentialsProvider`, but worth cross-checking and documenting

**Comment by loicmathieu** [comment]
We already use the `DefaultCredentialsProvider`  that is documented to use the following:
 *   <li>Java System Properties - {@code aws.accessKeyId} and {@code aws.secretAccessKey}</li>
 *   <li>Environment Variables - {@code AWS_ACCESS_KEY_ID} and {@code AWS_SECRET_ACCESS_KEY}</li>
 *   <li>Web Identity Token credentials from system properties or environment variables</li>
 *   <li>Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI</li>
 *   <li>Credentials delivered through the Amazon EC2 container service if AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" environment
 *   variable is set and security manager has permission to access the variable,</li>
 *   <li>Instance profile credentials delivered through the Amazon EC2 metadata service</li>

All task properties that allow configuring credentials have this description:
```
"If no connection is defined, we will use the `DefaultCredentialsProvider` to fetch the value."
```

What I can do is to change it to link to this page of the AWS documentation instead: 
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html

I can also add a global guide in the plugin to better explain how to authenticate as we have for the GCP plugin.

**Comment by loicmathieu** [comment]
In fact there is already a documentation at the root, I'll improve it.
