### ISSUE TITLE
Amazon Athena

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-aws#44]
### Feature description

Amazon Athena

**Comment by loicmathieu** [comment]
Link to the SDK https://docs.aws.amazon.com/athena/latest/ug/code-samples.html

**Comment by anna-geller** [comment]
just a note for posterity: if JDBC Athena task would be added too, here is a proper URL that would be needed:


```bash
jdbc:awsathena://AwsRegion=[REGION];UID=[ACCESS KEY];PWD=[SECRET KEY];S3OutputLocation=[LOCATION]

# relying on a preconfigured AWS CLI profile:
jdbc:awsathena://AwsRegion=eu-central-1;S3OutputLocation=s3://declarative-orchestration/athena/
```

Link to the driver: https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html
