### ISSUE TITLE
Investigate a more cost-effective alternative RealTime trigger implementation for AWS SQS

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#464]
> you need to call `receiveMessage` periodically manually, atm there is no way to listen to an SQS queue in real-time without paying a very high cost. We already have a polling of 100ms, if we configure waitTime we could remove it

**Comment by loicmathieu** [comment]
## Implementation details

We need to use `receiveRequest.waitTimeSeconds()` to wait for messages instead of ending immediately when no messages to lower the number of API calls.

Doing so, we may be able to remove the `Thread.sleep()` in the busy loop.
