### ISSUE TITLE
Deprecate maxNumberOfMessage in SQS RealTimeTrigger (or change default value to 1)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#568]
### Feature description

Real-time should react in real-time for each message, so this property seems confusing/not fitting into real-time trigger. If we prefer, maybe we can keep it but set the default to 1 instead of 5?

**Comment by fhussonnois** [comment]
No we must not deprecate this property. This property defines the max number of messages returned per request to SQS Reducing the value to 1 will increase the number of requests made to SQS and so cost, as well as latency. 

Most of queuing/messaging system have a batching mechanism for consumption to increase performance.

In any case , realtime triggers always create one execution per message.

**Comment by anna-geller** [comment]
strange, if the maxNumberOfMessage is set to 5, I imagined this would create 1 execution per 5 messages. I'll clarify in the docs and close the issue then. Thanks Florian!
